// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package player_money

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PlayerMoneyServiceClient is the client API for PlayerMoneyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlayerMoneyServiceClient interface {
	// StreamCreatePlayerMoneyData streams multiple player money data records
	// Client sends multiple requests, server responds with created records
	StreamCreatePlayerMoneyData(ctx context.Context, opts ...grpc.CallOption) (PlayerMoneyService_StreamCreatePlayerMoneyDataClient, error)
	// StreamGetPlayerMoneyDataBySeed streams all player money data for a seed
	// Client sends a seed request, server streams back all matching records
	StreamGetPlayerMoneyDataBySeed(ctx context.Context, in *GetBySeedRequest, opts ...grpc.CallOption) (PlayerMoneyService_StreamGetPlayerMoneyDataBySeedClient, error)
	// StreamGetAllPlayerMoneyData streams all player money data with pagination
	// Client sends pagination request, server streams back records
	StreamGetAllPlayerMoneyData(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (PlayerMoneyService_StreamGetAllPlayerMoneyDataClient, error)
	// StreamGetPlayerMoneyDataByTimecode streams player money data by timecode
	// Client sends timecode request, server streams back matching records
	StreamGetPlayerMoneyDataByTimecode(ctx context.Context, in *GetByTimecodeRequest, opts ...grpc.CallOption) (PlayerMoneyService_StreamGetPlayerMoneyDataByTimecodeClient, error)
}

type playerMoneyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlayerMoneyServiceClient(cc grpc.ClientConnInterface) PlayerMoneyServiceClient {
	return &playerMoneyServiceClient{cc}
}

func (c *playerMoneyServiceClient) StreamCreatePlayerMoneyData(ctx context.Context, opts ...grpc.CallOption) (PlayerMoneyService_StreamCreatePlayerMoneyDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &PlayerMoneyService_ServiceDesc.Streams[0], "/player_money.PlayerMoneyService/StreamCreatePlayerMoneyData", opts...)
	if err != nil {
		return nil, err
	}
	x := &playerMoneyServiceStreamCreatePlayerMoneyDataClient{stream}
	return x, nil
}

type PlayerMoneyService_StreamCreatePlayerMoneyDataClient interface {
	Send(*MoneyDataRequest) error
	Recv() (*MoneyDataResponse, error)
	grpc.ClientStream
}

type playerMoneyServiceStreamCreatePlayerMoneyDataClient struct {
	grpc.ClientStream
}

func (x *playerMoneyServiceStreamCreatePlayerMoneyDataClient) Send(m *MoneyDataRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *playerMoneyServiceStreamCreatePlayerMoneyDataClient) Recv() (*MoneyDataResponse, error) {
	m := new(MoneyDataResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *playerMoneyServiceClient) StreamGetPlayerMoneyDataBySeed(ctx context.Context, in *GetBySeedRequest, opts ...grpc.CallOption) (PlayerMoneyService_StreamGetPlayerMoneyDataBySeedClient, error) {
	stream, err := c.cc.NewStream(ctx, &PlayerMoneyService_ServiceDesc.Streams[1], "/player_money.PlayerMoneyService/StreamGetPlayerMoneyDataBySeed", opts...)
	if err != nil {
		return nil, err
	}
	x := &playerMoneyServiceStreamGetPlayerMoneyDataBySeedClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PlayerMoneyService_StreamGetPlayerMoneyDataBySeedClient interface {
	Recv() (*MoneyDataResponse, error)
	grpc.ClientStream
}

type playerMoneyServiceStreamGetPlayerMoneyDataBySeedClient struct {
	grpc.ClientStream
}

func (x *playerMoneyServiceStreamGetPlayerMoneyDataBySeedClient) Recv() (*MoneyDataResponse, error) {
	m := new(MoneyDataResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *playerMoneyServiceClient) StreamGetAllPlayerMoneyData(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (PlayerMoneyService_StreamGetAllPlayerMoneyDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &PlayerMoneyService_ServiceDesc.Streams[2], "/player_money.PlayerMoneyService/StreamGetAllPlayerMoneyData", opts...)
	if err != nil {
		return nil, err
	}
	x := &playerMoneyServiceStreamGetAllPlayerMoneyDataClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PlayerMoneyService_StreamGetAllPlayerMoneyDataClient interface {
	Recv() (*MoneyDataResponse, error)
	grpc.ClientStream
}

type playerMoneyServiceStreamGetAllPlayerMoneyDataClient struct {
	grpc.ClientStream
}

func (x *playerMoneyServiceStreamGetAllPlayerMoneyDataClient) Recv() (*MoneyDataResponse, error) {
	m := new(MoneyDataResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *playerMoneyServiceClient) StreamGetPlayerMoneyDataByTimecode(ctx context.Context, in *GetByTimecodeRequest, opts ...grpc.CallOption) (PlayerMoneyService_StreamGetPlayerMoneyDataByTimecodeClient, error) {
	stream, err := c.cc.NewStream(ctx, &PlayerMoneyService_ServiceDesc.Streams[3], "/player_money.PlayerMoneyService/StreamGetPlayerMoneyDataByTimecode", opts...)
	if err != nil {
		return nil, err
	}
	x := &playerMoneyServiceStreamGetPlayerMoneyDataByTimecodeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PlayerMoneyService_StreamGetPlayerMoneyDataByTimecodeClient interface {
	Recv() (*MoneyDataResponse, error)
	grpc.ClientStream
}

type playerMoneyServiceStreamGetPlayerMoneyDataByTimecodeClient struct {
	grpc.ClientStream
}

func (x *playerMoneyServiceStreamGetPlayerMoneyDataByTimecodeClient) Recv() (*MoneyDataResponse, error) {
	m := new(MoneyDataResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PlayerMoneyServiceServer is the server API for PlayerMoneyService service.
// All implementations must embed UnimplementedPlayerMoneyServiceServer
// for forward compatibility
type PlayerMoneyServiceServer interface {
	// StreamCreatePlayerMoneyData streams multiple player money data records
	// Client sends multiple requests, server responds with created records
	StreamCreatePlayerMoneyData(PlayerMoneyService_StreamCreatePlayerMoneyDataServer) error
	// StreamGetPlayerMoneyDataBySeed streams all player money data for a seed
	// Client sends a seed request, server streams back all matching records
	StreamGetPlayerMoneyDataBySeed(*GetBySeedRequest, PlayerMoneyService_StreamGetPlayerMoneyDataBySeedServer) error
	// StreamGetAllPlayerMoneyData streams all player money data with pagination
	// Client sends pagination request, server streams back records
	StreamGetAllPlayerMoneyData(*GetAllRequest, PlayerMoneyService_StreamGetAllPlayerMoneyDataServer) error
	// StreamGetPlayerMoneyDataByTimecode streams player money data by timecode
	// Client sends timecode request, server streams back matching records
	StreamGetPlayerMoneyDataByTimecode(*GetByTimecodeRequest, PlayerMoneyService_StreamGetPlayerMoneyDataByTimecodeServer) error
	mustEmbedUnimplementedPlayerMoneyServiceServer()
}

// UnimplementedPlayerMoneyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPlayerMoneyServiceServer struct {
}

func (UnimplementedPlayerMoneyServiceServer) StreamCreatePlayerMoneyData(PlayerMoneyService_StreamCreatePlayerMoneyDataServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamCreatePlayerMoneyData not implemented")
}
func (UnimplementedPlayerMoneyServiceServer) StreamGetPlayerMoneyDataBySeed(*GetBySeedRequest, PlayerMoneyService_StreamGetPlayerMoneyDataBySeedServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamGetPlayerMoneyDataBySeed not implemented")
}
func (UnimplementedPlayerMoneyServiceServer) StreamGetAllPlayerMoneyData(*GetAllRequest, PlayerMoneyService_StreamGetAllPlayerMoneyDataServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamGetAllPlayerMoneyData not implemented")
}
func (UnimplementedPlayerMoneyServiceServer) StreamGetPlayerMoneyDataByTimecode(*GetByTimecodeRequest, PlayerMoneyService_StreamGetPlayerMoneyDataByTimecodeServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamGetPlayerMoneyDataByTimecode not implemented")
}
func (UnimplementedPlayerMoneyServiceServer) mustEmbedUnimplementedPlayerMoneyServiceServer() {}

// UnsafePlayerMoneyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlayerMoneyServiceServer will
// result in compilation errors.
type UnsafePlayerMoneyServiceServer interface {
	mustEmbedUnimplementedPlayerMoneyServiceServer()
}

func RegisterPlayerMoneyServiceServer(s grpc.ServiceRegistrar, srv PlayerMoneyServiceServer) {
	s.RegisterService(&PlayerMoneyService_ServiceDesc, srv)
}

func _PlayerMoneyService_StreamCreatePlayerMoneyData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PlayerMoneyServiceServer).StreamCreatePlayerMoneyData(&playerMoneyServiceStreamCreatePlayerMoneyDataServer{stream})
}

type PlayerMoneyService_StreamCreatePlayerMoneyDataServer interface {
	Send(*MoneyDataResponse) error
	Recv() (*MoneyDataRequest, error)
	grpc.ServerStream
}

type playerMoneyServiceStreamCreatePlayerMoneyDataServer struct {
	grpc.ServerStream
}

func (x *playerMoneyServiceStreamCreatePlayerMoneyDataServer) Send(m *MoneyDataResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *playerMoneyServiceStreamCreatePlayerMoneyDataServer) Recv() (*MoneyDataRequest, error) {
	m := new(MoneyDataRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PlayerMoneyService_StreamGetPlayerMoneyDataBySeed_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetBySeedRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PlayerMoneyServiceServer).StreamGetPlayerMoneyDataBySeed(m, &playerMoneyServiceStreamGetPlayerMoneyDataBySeedServer{stream})
}

type PlayerMoneyService_StreamGetPlayerMoneyDataBySeedServer interface {
	Send(*MoneyDataResponse) error
	grpc.ServerStream
}

type playerMoneyServiceStreamGetPlayerMoneyDataBySeedServer struct {
	grpc.ServerStream
}

func (x *playerMoneyServiceStreamGetPlayerMoneyDataBySeedServer) Send(m *MoneyDataResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _PlayerMoneyService_StreamGetAllPlayerMoneyData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetAllRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PlayerMoneyServiceServer).StreamGetAllPlayerMoneyData(m, &playerMoneyServiceStreamGetAllPlayerMoneyDataServer{stream})
}

type PlayerMoneyService_StreamGetAllPlayerMoneyDataServer interface {
	Send(*MoneyDataResponse) error
	grpc.ServerStream
}

type playerMoneyServiceStreamGetAllPlayerMoneyDataServer struct {
	grpc.ServerStream
}

func (x *playerMoneyServiceStreamGetAllPlayerMoneyDataServer) Send(m *MoneyDataResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _PlayerMoneyService_StreamGetPlayerMoneyDataByTimecode_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetByTimecodeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PlayerMoneyServiceServer).StreamGetPlayerMoneyDataByTimecode(m, &playerMoneyServiceStreamGetPlayerMoneyDataByTimecodeServer{stream})
}

type PlayerMoneyService_StreamGetPlayerMoneyDataByTimecodeServer interface {
	Send(*MoneyDataResponse) error
	grpc.ServerStream
}

type playerMoneyServiceStreamGetPlayerMoneyDataByTimecodeServer struct {
	grpc.ServerStream
}

func (x *playerMoneyServiceStreamGetPlayerMoneyDataByTimecodeServer) Send(m *MoneyDataResponse) error {
	return x.ServerStream.SendMsg(m)
}

// PlayerMoneyService_ServiceDesc is the grpc.ServiceDesc for PlayerMoneyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlayerMoneyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "player_money.PlayerMoneyService",
	HandlerType: (*PlayerMoneyServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamCreatePlayerMoneyData",
			Handler:       _PlayerMoneyService_StreamCreatePlayerMoneyData_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamGetPlayerMoneyDataBySeed",
			Handler:       _PlayerMoneyService_StreamGetPlayerMoneyDataBySeed_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamGetAllPlayerMoneyData",
			Handler:       _PlayerMoneyService_StreamGetAllPlayerMoneyData_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamGetPlayerMoneyDataByTimecode",
			Handler:       _PlayerMoneyService_StreamGetPlayerMoneyDataByTimecode_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/player_money.proto",
}
