// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/player_money.proto

package player_money

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 21)
)

type MoneyDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seed                     string          `protobuf:"bytes,1,opt,name=seed,proto3" json:"seed,omitempty"`
	Timecode                 int64           `protobuf:"varint,2,opt,name=timecode,proto3" json:"timecode,omitempty"`
	Money                    []int32         `protobuf:"varint,3,rep,packed,name=money,proto3" json:"money,omitempty"`
	MoneyEarned              []int32         `protobuf:"varint,4,rep,packed,name=money_earned,json=moneyEarned,proto3" json:"money_earned,omitempty"`
	UnitsBuilt               []int32         `protobuf:"varint,5,rep,packed,name=units_built,json=unitsBuilt,proto3" json:"units_built,omitempty"`
	UnitsLost                []int32         `protobuf:"varint,6,rep,packed,name=units_lost,json=unitsLost,proto3" json:"units_lost,omitempty"`
	BuildingsBuilt           []int32         `protobuf:"varint,7,rep,packed,name=buildings_built,json=buildingsBuilt,proto3" json:"buildings_built,omitempty"`
	BuildingsLost            []int32         `protobuf:"varint,8,rep,packed,name=buildings_lost,json=buildingsLost,proto3" json:"buildings_lost,omitempty"`
	BuildingsKilled          []*Int32Array8x8 `protobuf:"bytes,9,rep,name=buildings_killed,json=buildingsKilled,proto3" json:"buildings_killed,omitempty"`
	UnitsKilled              []*Int32Array8x8 `protobuf:"bytes,10,rep,name=units_killed,json=unitsKilled,proto3" json:"units_killed,omitempty"`
	GeneralsPointsTotal      []int32         `protobuf:"varint,11,rep,packed,name=generals_points_total,json=generalsPointsTotal,proto3" json:"generals_points_total,omitempty"`
	GeneralsPointsUsed       []int32         `protobuf:"varint,12,rep,packed,name=generals_points_used,json=generalsPointsUsed,proto3" json:"generals_points_used,omitempty"`
	RadarsBuilt              []int32         `protobuf:"varint,13,rep,packed,name=radars_built,json=radarsBuilt,proto3" json:"radars_built,omitempty"`
	SearchAndDestroy         []int32         `protobuf:"varint,14,rep,packed,name=search_and_destroy,json=searchAndDestroy,proto3" json:"search_and_destroy,omitempty"`
	HoldTheLine              []int32         `protobuf:"varint,15,rep,packed,name=hold_the_line,json=holdTheLine,proto3" json:"hold_the_line,omitempty"`
	Bombardment              []int32         `protobuf:"varint,16,rep,packed,name=bombardment,proto3" json:"bombardment,omitempty"`
	Xp                       []int32         `protobuf:"varint,17,rep,packed,name=xp,proto3" json:"xp,omitempty"`
	XpLevel                  []int32         `protobuf:"varint,18,rep,packed,name=xp_level,json=xpLevel,proto3" json:"xp_level,omitempty"`
	TechBuildingsCaptured    []int32         `protobuf:"varint,19,rep,packed,name=tech_buildings_captured,json=techBuildingsCaptured,proto3" json:"tech_buildings_captured,omitempty"`
	FactionBuildingsCaptured []int32         `protobuf:"varint,20,rep,packed,name=faction_buildings_captured,json=factionBuildingsCaptured,proto3" json:"faction_buildings_captured,omitempty"`
	PowerTotal               []int32         `protobuf:"varint,21,rep,packed,name=power_total,json=powerTotal,proto3" json:"power_total,omitempty"`
	PowerUsed                []int32         `protobuf:"varint,22,rep,packed,name=power_used,json=powerUsed,proto3" json:"power_used,omitempty"`
}

func (x *MoneyDataRequest) Reset() {
	*x = MoneyDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_player_money_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoneyDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoneyDataRequest) ProtoMessage() {}

func (x *MoneyDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_money_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MoneyDataRequest) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

func (x *MoneyDataRequest) GetTimecode() int64 {
	if x != nil {
		return x.Timecode
	}
	return 0
}

func (x *MoneyDataRequest) GetMoney() []int32 {
	if x != nil {
		return x.Money
	}
	return nil
}

func (x *MoneyDataRequest) GetMoneyEarned() []int32 {
	if x != nil {
		return x.MoneyEarned
	}
	return nil
}

func (x *MoneyDataRequest) GetUnitsBuilt() []int32 {
	if x != nil {
		return x.UnitsBuilt
	}
	return nil
}

func (x *MoneyDataRequest) GetUnitsLost() []int32 {
	if x != nil {
		return x.UnitsLost
	}
	return nil
}

func (x *MoneyDataRequest) GetBuildingsBuilt() []int32 {
	if x != nil {
		return x.BuildingsBuilt
	}
	return nil
}

func (x *MoneyDataRequest) GetBuildingsLost() []int32 {
	if x != nil {
		return x.BuildingsLost
	}
	return nil
}

func (x *MoneyDataRequest) GetBuildingsKilled() []*Int32Array8x8 {
	if x != nil {
		return x.BuildingsKilled
	}
	return nil
}

func (x *MoneyDataRequest) GetUnitsKilled() []*Int32Array8x8 {
	if x != nil {
		return x.UnitsKilled
	}
	return nil
}

func (x *MoneyDataRequest) GetGeneralsPointsTotal() []int32 {
	if x != nil {
		return x.GeneralsPointsTotal
	}
	return nil
}

func (x *MoneyDataRequest) GetGeneralsPointsUsed() []int32 {
	if x != nil {
		return x.GeneralsPointsUsed
	}
	return nil
}

func (x *MoneyDataRequest) GetRadarsBuilt() []int32 {
	if x != nil {
		return x.RadarsBuilt
	}
	return nil
}

func (x *MoneyDataRequest) GetSearchAndDestroy() []int32 {
	if x != nil {
		return x.SearchAndDestroy
	}
	return nil
}

func (x *MoneyDataRequest) GetHoldTheLine() []int32 {
	if x != nil {
		return x.HoldTheLine
	}
	return nil
}

func (x *MoneyDataRequest) GetBombardment() []int32 {
	if x != nil {
		return x.Bombardment
	}
	return nil
}

func (x *MoneyDataRequest) GetXp() []int32 {
	if x != nil {
		return x.Xp
	}
	return nil
}

func (x *MoneyDataRequest) GetXpLevel() []int32 {
	if x != nil {
		return x.XpLevel
	}
	return nil
}

func (x *MoneyDataRequest) GetTechBuildingsCaptured() []int32 {
	if x != nil {
		return x.TechBuildingsCaptured
	}
	return nil
}

func (x *MoneyDataRequest) GetFactionBuildingsCaptured() []int32 {
	if x != nil {
		return x.FactionBuildingsCaptured
	}
	return nil
}

func (x *MoneyDataRequest) GetPowerTotal() []int32 {
	if x != nil {
		return x.PowerTotal
	}
	return nil
}

func (x *MoneyDataRequest) GetPowerUsed() []int32 {
	if x != nil {
		return x.PowerUsed
	}
	return nil
}

type Int32Array8x8 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []int32 `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *Int32Array8x8) Reset() {
	*x = Int32Array8x8{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_player_money_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Int32Array8x8) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int32Array8x8) ProtoMessage() {}

func (x *Int32Array8x8) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_money_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Int32Array8x8) GetValues() []int32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type MoneyDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                       uint32          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Seed                     string          `protobuf:"bytes,2,opt,name=seed,proto3" json:"seed,omitempty"`
	Timecode                 int32           `protobuf:"varint,3,opt,name=timecode,proto3" json:"timecode,omitempty"`
	Player1Money             int32           `protobuf:"varint,4,opt,name=player_1_money,json=player1Money,proto3" json:"player_1_money,omitempty"`
	Player2Money             int32           `protobuf:"varint,5,opt,name=player_2_money,json=player2Money,proto3" json:"player_2_money,omitempty"`
	Player3Money             int32           `protobuf:"varint,6,opt,name=player_3_money,json=player3Money,proto3" json:"player_3_money,omitempty"`
	Player4Money             int32           `protobuf:"varint,7,opt,name=player_4_money,json=player4Money,proto3" json:"player_4_money,omitempty"`
	Player5Money             int32           `protobuf:"varint,8,opt,name=player_5_money,json=player5Money,proto3" json:"player_5_money,omitempty"`
	Player6Money             int32           `protobuf:"varint,9,opt,name=player_6_money,json=player6Money,proto3" json:"player_6_money,omitempty"`
	Player7Money             int32           `protobuf:"varint,10,opt,name=player_7_money,json=player7Money,proto3" json:"player_7_money,omitempty"`
	Player8Money             int32           `protobuf:"varint,11,opt,name=player_8_money,json=player8Money,proto3" json:"player_8_money,omitempty"`
	MoneyEarned              []int32         `protobuf:"varint,12,rep,packed,name=money_earned,json=moneyEarned,proto3" json:"money_earned,omitempty"`
	UnitsBuilt               []int32         `protobuf:"varint,13,rep,packed,name=units_built,json=unitsBuilt,proto3" json:"units_built,omitempty"`
	UnitsLost                []int32         `protobuf:"varint,14,rep,packed,name=units_lost,json=unitsLost,proto3" json:"units_lost,omitempty"`
	BuildingsBuilt           []int32         `protobuf:"varint,15,rep,packed,name=buildings_built,json=buildingsBuilt,proto3" json:"buildings_built,omitempty"`
	BuildingsLost            []int32         `protobuf:"varint,16,rep,packed,name=buildings_lost,json=buildingsLost,proto3" json:"buildings_lost,omitempty"`
	BuildingsKilled          []*Int32Array8x8 `protobuf:"bytes,17,rep,name=buildings_killed,json=buildingsKilled,proto3" json:"buildings_killed,omitempty"`
	UnitsKilled              []*Int32Array8x8 `protobuf:"bytes,18,rep,name=units_killed,json=unitsKilled,proto3" json:"units_killed,omitempty"`
	GeneralsPointsTotal      []int32         `protobuf:"varint,19,rep,packed,name=generals_points_total,json=generalsPointsTotal,proto3" json:"generals_points_total,omitempty"`
	GeneralsPointsUsed       []int32         `protobuf:"varint,20,rep,name=generals_points_used,json=generalsPointsUsed,proto3" json:"generals_points_used,omitempty"`
	RadarsBuilt              []int32         `protobuf:"varint,21,rep,name=radars_built,json=radarsBuilt,proto3" json:"radars_built,omitempty"`
	SearchAndDestroy         []int32         `protobuf:"varint,22,rep,name=search_and_destroy,json=searchAndDestroy,proto3" json:"search_and_destroy,omitempty"`
	HoldTheLine              []int32         `protobuf:"varint,23,rep,name=hold_the_line,json=holdTheLine,proto3" json:"hold_the_line,omitempty"`
	Bombardment              []int32         `protobuf:"varint,24,rep,name=bombardment,proto3" json:"bombardment,omitempty"`
	Xp                       []int32         `protobuf:"varint,25,rep,name=xp,proto3" json:"xp,omitempty"`
	XpLevel                  []int32         `protobuf:"varint,26,rep,name=xp_level,json=xpLevel,proto3" json:"xp_level,omitempty"`
	TechBuildingsCaptured    []int32         `protobuf:"varint,27,rep,name=tech_buildings_captured,json=techBuildingsCaptured,proto3" json:"tech_buildings_captured,omitempty"`
	FactionBuildingsCaptured []int32         `protobuf:"varint,28,rep,name=faction_buildings_captured,json=factionBuildingsCaptured,proto3" json:"faction_buildings_captured,omitempty"`
	PowerTotal               []int32         `protobuf:"varint,29,rep,name=power_total,json=powerTotal,proto3" json:"power_total,omitempty"`
	PowerUsed                []int32         `protobuf:"varint,30,rep,name=power_used,json=powerUsed,proto3" json:"power_used,omitempty"`
	CreatedAt                int64           `protobuf:"varint,31,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt                int64           `protobuf:"varint,32,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *MoneyDataResponse) Reset() {
	*x = MoneyDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_player_money_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoneyDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoneyDataResponse) ProtoMessage() {}

func (x *MoneyDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_money_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MoneyDataResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MoneyDataResponse) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

func (x *MoneyDataResponse) GetTimecode() int32 {
	if x != nil {
		return x.Timecode
	}
	return 0
}

func (x *MoneyDataResponse) GetPlayer1Money() int32 {
	if x != nil {
		return x.Player1Money
	}
	return 0
}

func (x *MoneyDataResponse) GetPlayer2Money() int32 {
	if x != nil {
		return x.Player2Money
	}
	return 0
}

func (x *MoneyDataResponse) GetPlayer3Money() int32 {
	if x != nil {
		return x.Player3Money
	}
	return 0
}

func (x *MoneyDataResponse) GetPlayer4Money() int32 {
	if x != nil {
		return x.Player4Money
	}
	return 0
}

func (x *MoneyDataResponse) GetPlayer5Money() int32 {
	if x != nil {
		return x.Player5Money
	}
	return 0
}

func (x *MoneyDataResponse) GetPlayer6Money() int32 {
	if x != nil {
		return x.Player6Money
	}
	return 0
}

func (x *MoneyDataResponse) GetPlayer7Money() int32 {
	if x != nil {
		return x.Player7Money
	}
	return 0
}

func (x *MoneyDataResponse) GetPlayer8Money() int32 {
	if x != nil {
		return x.Player8Money
	}
	return 0
}

func (x *MoneyDataResponse) GetMoneyEarned() []int32 {
	if x != nil {
		return x.MoneyEarned
	}
	return nil
}

func (x *MoneyDataResponse) GetUnitsBuilt() []int32 {
	if x != nil {
		return x.UnitsBuilt
	}
	return nil
}

func (x *MoneyDataResponse) GetUnitsLost() []int32 {
	if x != nil {
		return x.UnitsLost
	}
	return nil
}

func (x *MoneyDataResponse) GetBuildingsBuilt() []int32 {
	if x != nil {
		return x.BuildingsBuilt
	}
	return nil
}

func (x *MoneyDataResponse) GetBuildingsLost() []int32 {
	if x != nil {
		return x.BuildingsLost
	}
	return nil
}

func (x *MoneyDataResponse) GetBuildingsKilled() []*Int32Array8x8 {
	if x != nil {
		return x.BuildingsKilled
	}
	return nil
}

func (x *MoneyDataResponse) GetUnitsKilled() []*Int32Array8x8 {
	if x != nil {
		return x.UnitsKilled
	}
	return nil
}

func (x *MoneyDataResponse) GetGeneralsPointsTotal() []int32 {
	if x != nil {
		return x.GeneralsPointsTotal
	}
	return nil
}

func (x *MoneyDataResponse) GetGeneralsPointsUsed() []int32 {
	if x != nil {
		return x.GeneralsPointsUsed
	}
	return nil
}

func (x *MoneyDataResponse) GetRadarsBuilt() []int32 {
	if x != nil {
		return x.RadarsBuilt
	}
	return nil
}

func (x *MoneyDataResponse) GetSearchAndDestroy() []int32 {
	if x != nil {
		return x.SearchAndDestroy
	}
	return nil
}

func (x *MoneyDataResponse) GetHoldTheLine() []int32 {
	if x != nil {
		return x.HoldTheLine
	}
	return nil
}

func (x *MoneyDataResponse) GetBombardment() []int32 {
	if x != nil {
		return x.Bombardment
	}
	return nil
}

func (x *MoneyDataResponse) GetXp() []int32 {
	if x != nil {
		return x.Xp
	}
	return nil
}

func (x *MoneyDataResponse) GetXpLevel() []int32 {
	if x != nil {
		return x.XpLevel
	}
	return nil
}

func (x *MoneyDataResponse) GetTechBuildingsCaptured() []int32 {
	if x != nil {
		return x.TechBuildingsCaptured
	}
	return nil
}

func (x *MoneyDataResponse) GetFactionBuildingsCaptured() []int32 {
	if x != nil {
		return x.FactionBuildingsCaptured
	}
	return nil
}

func (x *MoneyDataResponse) GetPowerTotal() []int32 {
	if x != nil {
		return x.PowerTotal
	}
	return nil
}

func (x *MoneyDataResponse) GetPowerUsed() []int32 {
	if x != nil {
		return x.PowerUsed
	}
	return nil
}

func (x *MoneyDataResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *MoneyDataResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type GetBySeedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seed string `protobuf:"bytes,1,opt,name=seed,proto3" json:"seed,omitempty"`
}

func (x *GetBySeedRequest) Reset() {
	*x = GetBySeedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_player_money_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBySeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBySeedRequest) ProtoMessage() {}

func (x *GetBySeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_money_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetBySeedRequest) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

type GetAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit  int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset int32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_player_money_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_money_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetAllRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetByTimecodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timecode int32 `protobuf:"varint,1,opt,name=timecode,proto3" json:"timecode,omitempty"`
}

func (x *GetByTimecodeRequest) Reset() {
	*x = GetByTimecodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_player_money_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetByTimecodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByTimecodeRequest) ProtoMessage() {}

func (x *GetByTimecodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_money_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetByTimecodeRequest) GetTimecode() int32 {
	if x != nil {
		return x.Timecode
	}
	return 0
}

var File_proto_player_money_proto protoreflect.FileDescriptor

var file_proto_player_money_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x6d,
	0x6f, 0x6e, 0x65, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_player_money_proto_rawDescOnce sync.Once
	file_proto_player_money_proto_rawDescData = file_proto_player_money_proto_rawDesc
)

func file_proto_player_money_proto_rawDescGZIP() []byte {
	file_proto_player_money_proto_rawDescOnce.Do(func() {
		file_proto_player_money_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_player_money_proto_rawDescData)
	})
	return file_proto_player_money_proto_rawDescData
}

var file_proto_player_money_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_player_money_proto_goTypes = []interface{}{
	(*MoneyDataRequest)(nil),     // 0: player_money.MoneyDataRequest
	(*Int32Array8x8)(nil),        // 1: player_money.Int32Array8x8
	(*MoneyDataResponse)(nil),    // 2: player_money.MoneyDataResponse
	(*GetBySeedRequest)(nil),     // 3: player_money.GetBySeedRequest
	(*GetAllRequest)(nil),         // 4: player_money.GetAllRequest
	(*GetByTimecodeRequest)(nil), // 5: player_money.GetByTimecodeRequest
}

func init() { file_proto_player_money_proto_init() }
func file_proto_player_money_proto_init() {
	if File_proto_player_money_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_player_money_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoneyDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_player_money_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Int32Array8x8); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_player_money_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoneyDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_player_money_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBySeedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_player_money_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_player_money_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetByTimecodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_player_money_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_player_money_proto_goTypes,
		DependencyIndexes: file_proto_player_money_proto_depIdxs,
		MessageInfos:      file_proto_player_money_proto_msgTypes,
	}.Build()
	File_proto_player_money_proto = out.File
	file_proto_player_money_proto_rawDesc = nil
	file_proto_player_money_proto_goTypes = nil
}

var file_proto_player_money_proto_depIdxs = []int32{
	0, // 0: player_money.PlayerMoneyService.StreamCreatePlayerMoneyData:input_type -> player_money.MoneyDataRequest
	3, // 1: player_money.PlayerMoneyService.StreamGetPlayerMoneyDataBySeed:input_type -> player_money.GetBySeedRequest
	4, // 2: player_money.PlayerMoneyService.StreamGetAllPlayerMoneyData:input_type -> player_money.GetAllRequest
	5, // 3: player_money.PlayerMoneyService.StreamGetPlayerMoneyDataByTimecode:input_type -> player_money.GetByTimecodeRequest
	2, // 4: player_money.PlayerMoneyService.StreamCreatePlayerMoneyData:output_type -> player_money.MoneyDataResponse
	2, // 5: player_money.PlayerMoneyService.StreamGetPlayerMoneyDataBySeed:output_type -> player_money.MoneyDataResponse
	2, // 6: player_money.PlayerMoneyService.StreamGetAllPlayerMoneyData:output_type -> player_money.MoneyDataResponse
	2, // 7: player_money.PlayerMoneyService.StreamGetPlayerMoneyDataByTimecode:output_type -> player_money.MoneyDataResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_player_money_proto_init() }
