// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: player_money.proto

package player_money

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlayerMoneyService_StreamCreatePlayerMoneyData_FullMethodName        = "/player_money.PlayerMoneyService/StreamCreatePlayerMoneyData"
	PlayerMoneyService_StreamGetPlayerMoneyDataBySeed_FullMethodName     = "/player_money.PlayerMoneyService/StreamGetPlayerMoneyDataBySeed"
	PlayerMoneyService_StreamGetAllPlayerMoneyData_FullMethodName        = "/player_money.PlayerMoneyService/StreamGetAllPlayerMoneyData"
	PlayerMoneyService_StreamGetPlayerMoneyDataByTimecode_FullMethodName = "/player_money.PlayerMoneyService/StreamGetPlayerMoneyDataByTimecode"
)

// PlayerMoneyServiceClient is the client API for PlayerMoneyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PlayerMoneyService provides streaming operations for player money data
type PlayerMoneyServiceClient interface {
	// StreamCreatePlayerMoneyData streams multiple player money data records
	// Client sends multiple requests, server responds with created records
	StreamCreatePlayerMoneyData(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MoneyDataRequest, MoneyDataResponse], error)
	// StreamGetPlayerMoneyDataBySeed streams all player money data for a seed
	// Client sends a seed request, server streams back all matching records
	StreamGetPlayerMoneyDataBySeed(ctx context.Context, in *GetBySeedRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MoneyDataResponse], error)
	// StreamGetAllPlayerMoneyData streams all player money data with pagination
	// Client sends pagination request, server streams back records
	StreamGetAllPlayerMoneyData(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MoneyDataResponse], error)
	// StreamGetPlayerMoneyDataByTimecode streams player money data by timecode
	// Client sends timecode request, server streams back matching records
	StreamGetPlayerMoneyDataByTimecode(ctx context.Context, in *GetByTimecodeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MoneyDataResponse], error)
}

type playerMoneyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlayerMoneyServiceClient(cc grpc.ClientConnInterface) PlayerMoneyServiceClient {
	return &playerMoneyServiceClient{cc}
}

func (c *playerMoneyServiceClient) StreamCreatePlayerMoneyData(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MoneyDataRequest, MoneyDataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PlayerMoneyService_ServiceDesc.Streams[0], PlayerMoneyService_StreamCreatePlayerMoneyData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MoneyDataRequest, MoneyDataResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlayerMoneyService_StreamCreatePlayerMoneyDataClient = grpc.BidiStreamingClient[MoneyDataRequest, MoneyDataResponse]

func (c *playerMoneyServiceClient) StreamGetPlayerMoneyDataBySeed(ctx context.Context, in *GetBySeedRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MoneyDataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PlayerMoneyService_ServiceDesc.Streams[1], PlayerMoneyService_StreamGetPlayerMoneyDataBySeed_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetBySeedRequest, MoneyDataResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlayerMoneyService_StreamGetPlayerMoneyDataBySeedClient = grpc.ServerStreamingClient[MoneyDataResponse]

func (c *playerMoneyServiceClient) StreamGetAllPlayerMoneyData(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MoneyDataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PlayerMoneyService_ServiceDesc.Streams[2], PlayerMoneyService_StreamGetAllPlayerMoneyData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetAllRequest, MoneyDataResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlayerMoneyService_StreamGetAllPlayerMoneyDataClient = grpc.ServerStreamingClient[MoneyDataResponse]

func (c *playerMoneyServiceClient) StreamGetPlayerMoneyDataByTimecode(ctx context.Context, in *GetByTimecodeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MoneyDataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PlayerMoneyService_ServiceDesc.Streams[3], PlayerMoneyService_StreamGetPlayerMoneyDataByTimecode_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetByTimecodeRequest, MoneyDataResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlayerMoneyService_StreamGetPlayerMoneyDataByTimecodeClient = grpc.ServerStreamingClient[MoneyDataResponse]

// PlayerMoneyServiceServer is the server API for PlayerMoneyService service.
// All implementations must embed UnimplementedPlayerMoneyServiceServer
// for forward compatibility.
//
// PlayerMoneyService provides streaming operations for player money data
type PlayerMoneyServiceServer interface {
	// StreamCreatePlayerMoneyData streams multiple player money data records
	// Client sends multiple requests, server responds with created records
	StreamCreatePlayerMoneyData(grpc.BidiStreamingServer[MoneyDataRequest, MoneyDataResponse]) error
	// StreamGetPlayerMoneyDataBySeed streams all player money data for a seed
	// Client sends a seed request, server streams back all matching records
	StreamGetPlayerMoneyDataBySeed(*GetBySeedRequest, grpc.ServerStreamingServer[MoneyDataResponse]) error
	// StreamGetAllPlayerMoneyData streams all player money data with pagination
	// Client sends pagination request, server streams back records
	StreamGetAllPlayerMoneyData(*GetAllRequest, grpc.ServerStreamingServer[MoneyDataResponse]) error
	// StreamGetPlayerMoneyDataByTimecode streams player money data by timecode
	// Client sends timecode request, server streams back matching records
	StreamGetPlayerMoneyDataByTimecode(*GetByTimecodeRequest, grpc.ServerStreamingServer[MoneyDataResponse]) error
	mustEmbedUnimplementedPlayerMoneyServiceServer()
}

// UnimplementedPlayerMoneyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlayerMoneyServiceServer struct{}

func (UnimplementedPlayerMoneyServiceServer) StreamCreatePlayerMoneyData(grpc.BidiStreamingServer[MoneyDataRequest, MoneyDataResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamCreatePlayerMoneyData not implemented")
}
func (UnimplementedPlayerMoneyServiceServer) StreamGetPlayerMoneyDataBySeed(*GetBySeedRequest, grpc.ServerStreamingServer[MoneyDataResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamGetPlayerMoneyDataBySeed not implemented")
}
func (UnimplementedPlayerMoneyServiceServer) StreamGetAllPlayerMoneyData(*GetAllRequest, grpc.ServerStreamingServer[MoneyDataResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamGetAllPlayerMoneyData not implemented")
}
func (UnimplementedPlayerMoneyServiceServer) StreamGetPlayerMoneyDataByTimecode(*GetByTimecodeRequest, grpc.ServerStreamingServer[MoneyDataResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamGetPlayerMoneyDataByTimecode not implemented")
}
func (UnimplementedPlayerMoneyServiceServer) mustEmbedUnimplementedPlayerMoneyServiceServer() {}
func (UnimplementedPlayerMoneyServiceServer) testEmbeddedByValue()                            {}

// UnsafePlayerMoneyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlayerMoneyServiceServer will
// result in compilation errors.
type UnsafePlayerMoneyServiceServer interface {
	mustEmbedUnimplementedPlayerMoneyServiceServer()
}

func RegisterPlayerMoneyServiceServer(s grpc.ServiceRegistrar, srv PlayerMoneyServiceServer) {
	// If the following call panics, it indicates UnimplementedPlayerMoneyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlayerMoneyService_ServiceDesc, srv)
}

func _PlayerMoneyService_StreamCreatePlayerMoneyData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PlayerMoneyServiceServer).StreamCreatePlayerMoneyData(&grpc.GenericServerStream[MoneyDataRequest, MoneyDataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlayerMoneyService_StreamCreatePlayerMoneyDataServer = grpc.BidiStreamingServer[MoneyDataRequest, MoneyDataResponse]

func _PlayerMoneyService_StreamGetPlayerMoneyDataBySeed_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetBySeedRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PlayerMoneyServiceServer).StreamGetPlayerMoneyDataBySeed(m, &grpc.GenericServerStream[GetBySeedRequest, MoneyDataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlayerMoneyService_StreamGetPlayerMoneyDataBySeedServer = grpc.ServerStreamingServer[MoneyDataResponse]

func _PlayerMoneyService_StreamGetAllPlayerMoneyData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetAllRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PlayerMoneyServiceServer).StreamGetAllPlayerMoneyData(m, &grpc.GenericServerStream[GetAllRequest, MoneyDataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlayerMoneyService_StreamGetAllPlayerMoneyDataServer = grpc.ServerStreamingServer[MoneyDataResponse]

func _PlayerMoneyService_StreamGetPlayerMoneyDataByTimecode_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetByTimecodeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PlayerMoneyServiceServer).StreamGetPlayerMoneyDataByTimecode(m, &grpc.GenericServerStream[GetByTimecodeRequest, MoneyDataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlayerMoneyService_StreamGetPlayerMoneyDataByTimecodeServer = grpc.ServerStreamingServer[MoneyDataResponse]

// PlayerMoneyService_ServiceDesc is the grpc.ServiceDesc for PlayerMoneyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlayerMoneyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "player_money.PlayerMoneyService",
	HandlerType: (*PlayerMoneyServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamCreatePlayerMoneyData",
			Handler:       _PlayerMoneyService_StreamCreatePlayerMoneyData_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamGetPlayerMoneyDataBySeed",
			Handler:       _PlayerMoneyService_StreamGetPlayerMoneyDataBySeed_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamGetAllPlayerMoneyData",
			Handler:       _PlayerMoneyService_StreamGetAllPlayerMoneyData_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamGetPlayerMoneyDataByTimecode",
			Handler:       _PlayerMoneyService_StreamGetPlayerMoneyDataByTimecode_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "player_money.proto",
}
